import React from 'react';
import { OFFICIAL_LOGO_PATH, DEFAULT_BRANDING } from '../../lib/branding';
import { BrandLogo } from './BrandLogo';

interface ReportWatermarkProps {
  opacity?: number; // default subtle 0.06
  className?: string;
  size?: 'sm' | 'md' | 'lg';
}

/**
 * Centralized, reusable watermark system using the uploaded official Fahad's Tutorial logo.
 * 
 * Works across both:
 * 1. Screen Print-Preview (centered behind report content)
 * 2. Multi-page Browser Printing: Uses `position: fixed` in `@media print` so the browser's
 *    paged-media renderer repeats the watermark on Page 1, Page 2, Page 3, Page 4... across every single page.
 */
export const ReportWatermark: React.FC<ReportWatermarkProps> = ({
  opacity = DEFAULT_BRANDING.defaultWatermarkOpacity,
  className = '',
  size = 'md',
}) => {
  const sizeClasses = {
    sm: 'w-64 h-64 max-w-[40%]',
    md: 'w-96 h-96 max-w-[55%]',
    lg: 'w-[450px] h-[450px] max-w-[65%]',
  };

  return (
    <>
      {/* On-screen Report Preview Watermark (relative to report container) */}
      <div
        className={`pointer-events-none absolute inset-0 flex items-center justify-center overflow-hidden z-0 select-none print:hidden ${className}`}
        aria-hidden="true"
      >
        <div
          className={`${sizeClasses[size]} aspect-square flex items-center justify-center transition-opacity`}
          style={{ opacity }}
        >
          <img
            src={OFFICIAL_LOGO_PATH}
            alt="Watermark"
            className="w-full h-full object-contain"
            onError={(e) => {
              const target = e.target as HTMLImageElement;
              if (!target.src.includes('images.jpg')) {
                target.src = '/assets/images.jpg';
              }
            }}
          />
        </div>
      </div>

      {/* Multi-Page Print Watermark: Repeats on EVERY printed page via CSS fixed paged media */}
      <div
        className="hidden print:flex fixed inset-0 pointer-events-none items-center justify-center z-[-1] select-none"
        aria-hidden="true"
        style={{ opacity }}
      >
        <div className="w-[120mm] h-[120mm] max-w-[60vw] max-h-[60vh] aspect-square flex items-center justify-center">
          <img
            src={OFFICIAL_LOGO_PATH}
            alt="Print Watermark"
            className="w-full h-full object-contain"
          />
        </div>
      </div>
    </>
  );
};

interface ReportHeaderProps {
  title: string;
  period?: string;
  generatedBy?: string;
  filterInfo?: string;
  className?: string;
}

/**
 * Standardized Official Report Header containing:
 * - Official Fahads Tutorial Logo
 * - Fahads Tutorial name & SSP branding
 * - Report Title
 * - Date/reporting period
 * - Generated date/time & generated by
 */
export const ReportHeader: React.FC<ReportHeaderProps> = ({
  title,
  period,
  generatedBy = 'Ananya Rahman (Head of SSP)',
  filterInfo,
  className = '',
}) => {
  return (
    <div className={`relative z-10 flex items-start justify-between border-b-2 border-slate-900 pb-5 mb-6 ${className}`}>
      <div className="flex items-center gap-3.5">
        {/* Official Circular Logo */}
        <BrandLogo size="lg" showSubtitle={false} />
        <div>
          <h1 className="text-xl font-black text-slate-950 tracking-tight leading-none uppercase">
            Fahad's Tutorial
          </h1>
          <p className="text-xs font-bold text-rose-600 tracking-wide mt-1 uppercase">
            Student Support Program (SSP) Management System
          </p>
          <p className="text-[11px] text-slate-500 font-medium">
            School of Digital Education • Mirpur, Dhaka
          </p>
        </div>
      </div>

      <div className="text-right text-xs space-y-1">
        <span className="inline-block px-3 py-1 bg-slate-900 text-white font-bold rounded-md uppercase tracking-wider text-[11px]">
          {title}
        </span>
        {period && (
          <p className="font-semibold text-slate-800 mt-1">Period: {period}</p>
        )}
        <p className="text-slate-500 text-[10px]">
          Generated: {new Date().toLocaleString()}
        </p>
        <p className="text-slate-500 text-[10px]">
          Generated By: <span className="font-medium text-slate-700">{generatedBy}</span>
        </p>
        {filterInfo && (
          <p className="text-slate-400 text-[9px] italic">Filters: {filterInfo}</p>
        )}
      </div>
    </div>
  );
};
